kafka:
  bootstrap-servers: localhost:9092

feature:
  statement-consumer:
    enabled: true

logging:
  level:
    root: INFO

server:
  port: 8082

spring:
  profiles:
    active: mock

  data:
    mongodb:
      uri: mongodb://localhost:27017/statement_db