spring:
  data:
    mongodb:
      uri: mongodb://mongodb:27017/statement_db

  datasource:
    url: jdbc:postgresql://postgres:5432/payment_db
    username: payment_user
    password: payment_pass
    driver-class-name: org.postgresql.Driver
