spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/statement_db
  
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false


server:
  port: 8083

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true